BLOC-580 Add Preview Buttons to Message Components / EUA List
bluehalo/ngx-starter pull request #178
Opened 2020-12-03 22:17 UTC by ltherrien

**Changes**
* Added preview button to base message and message list template
* Added preview drop-down item to EUA list template
* Added event handlers to pop up modal previewing title / content as HTML
* Added tests

**How to Verify**
* Go to the message list
* Create a message
* Verify that you can click the preview button in the message screen
* Go back to the message list
* Verify that the hamburger menu for a message shows a preview option (which opens the same modal)
* Go to the EUA list
* Create an EUA (the preview button here already existed)
* Go back to the EUA list
* Verify that the hamburger menu for an EUA shows a preview option (which opens a modal)

2020-12-04 21:33 UTC, jrassa requested changes
Looks good.  Will merge once the `console.log` line is removed.

2020-12-04 21:33 UTC, jrassa commented on src/app/core/admin/end-user-agreement/admin-list-euas.component.ts
> +		console.log(endUserAgreement);
Can we remove this?

2020-12-04 21:40 UTC, ltherrien commented on src/app/core/admin/end-user-agreement/admin-list-euas.component.ts
> +		console.log(endUserAgreement);
Good catch! Sorry!

2020-12-07 20:07 UTC, brianghig approved these changes

2020-12-07 20:08 UTC, brianghig approved these changes

2020-12-07 20:09 UTC, merged