refactor: Abstract CRUD+ functionality into base service class
bluehalo/ngx-starter pull request #279
Opened 2022-08-23 19:47 UTC by jrassa

2022-08-25 11:59 UTC, jrassa commented
Depends on bluehalo/node-rest-starter#191.

2022-08-26 04:14 UTC, brianghig requested changes

2022-08-26 04:14 UTC, brianghig commented on src/app/core/teams/teams.service.ts
> +			.put(
@jrassa - with the server-side change to make this a POST, this line needs to also stay as a POST vs. PUT.

2022-08-26 04:41 UTC, brianghig commented
Changes look great to me otherwise! Nice work @jrassa 

Tested and verified UI functionality, except for two issues around the feedback flyout:
1. When submitting "Ask a Question or Comment" feedback, the classification from the dropdown is lost. The field is an empty string when returned from the UI's API.
2. During that same submission, "undefined" is prepended to the "body" attribute. This string is carrying through to the feedback record stored in the database.

2022-08-26 11:35 UTC, jrassa commented on src/app/core/teams/teams.service.ts
> +			.put(
Fixed.  Originally, I started switching the other endpoints to use PUT, then realized that teams was the only one using PUT, so switched back to POST.  Missed updating this.

2022-08-26 11:45 UTC, jrassa commented
> Changes look great to me otherwise! Nice work @jrassa
> 
> Tested and verified UI functionality, except for two issues around the feedback flyout:
> 
> 1. When submitting "Ask a Question or Comment" feedback, the classification from the dropdown is lost. The field is an empty string when returned from the UI's API.
> 2. During that same submission, "undefined" is prepended to the "body" attribute. This string is carrying through to the feedback record stored in the database.

I think this may be a configuration issue on your end.

I have the feedback classifications configured as follows and it is working properly for me.
```
feedback: {
	showFlyout: true,
	showInSidebar: true,

	classificationOpts: [
		{ level: 'LEVEL-1', prefix: '(L1)' },
		{ level: 'LEVEL-2', prefix: '(L2)' },
		{ level: 'LEVEL-3', prefix: '(L3)' }
	]
},
```

However, if I changed it to have just strings, then I see the behavior that you are describing.

```
feedback: {
	showFlyout: true,
	showInSidebar: true,

	classificationOpts: [
		'LEVEL-1',
		'LEVEL-2'
	]
},
```

2022-08-26 12:06 UTC, brianghig commented
> I think this may be a configuration issue on your end.

@jrassa - you're absolutely right! Changes look good to me. Thanks for this clean + consistent update.

2022-08-26 12:06 UTC, brianghig approved these changes
LGTM

2022-08-26 20:08 UTC, merged