Update Font Awesome to 6.2.1
bluehalo/ngx-starter pull request #294
Opened 2023-01-04 22:27 UTC by josie-kaufman-bluehalo

This fix updates FA to the latest version 6.2.1 from 4.7. Also allows for backwards compatibility for faV4 and faV5.

Updates have been made to icons with naming convention suffix "-o" to reflect new naming conventions.

2023-01-06 13:47 UTC, jrassa commented
What version of node/npm are you using?  `package-lock.json` was changed to an older format.  On install, npm then upgraded back to the current format.  Should be using node 16.* and npm 8.*.  Can you switch versions and rerun `npm install`? The result is a much smaller diff.

2023-01-06 13:48 UTC, jrassa commented
> Updates have been made to icons with naming convention suffix "-o" to reflect new naming conventions.

These all should have all had `fa` replaced with `fa-regular` to maintain the outline style.

2023-01-06 14:04 UTC, jrassa commented
Sizing of Feedback flyout button is off.  Properly due to size difference with updated arrow icons.  Arrow should be inline with `Feedback`

![Screen Shot 2023-01-06 at 9 04 14 AM](https://user-images.githubusercontent.com/23661980/211027745-7439cf9a-72ef-480a-873c-ea7f1257cca6.png)

2023-01-06 14:05 UTC, jrassa requested changes

2023-01-06 14:05 UTC, jrassa commented on src/styles/ngx-bootstrap/_cards.scss
> +			font: var(--fa-font-solid);; /* stylelint-disable-line */
Need to maintain the specified font-size.  May need to use a separate `font-size` style declaration.

2023-01-06 14:05 UTC, jrassa commented on src/styles/_selection.scss
> +				font: var(--fa-font-solid);
Need to maintain the specified font-size.  May need to use a separate `font-size` style declaration.

2023-01-13 19:02 UTC, josie-kaufman-bluehalo commented
package-lock.json issue has been fixed.

2023-01-18 20:49 UTC, josie-kaufman-bluehalo commented on src/styles/ngx-bootstrap/_cards.scss
> +			font: var(--fa-font-solid);; /* stylelint-disable-line */
The font size calculation has been moved into a separate line.

2023-01-18 20:50 UTC, josie-kaufman-bluehalo commented on src/styles/_selection.scss
> +				font: var(--fa-font-solid);
The font size calculation has been moved into a separate line.

2023-01-18 22:16 UTC, josie-kaufman-bluehalo commented
Looking for some help with fixing the fonts of "Firefox" and "Chrome" in the browser recommendation section under the help tab. I think the styling of the text was lost in the upgrade and am unfamiliar with css Pseudo-elements.
Before:
<img width="382" alt="Screen Shot 2023-01-18 at 3 51 18 PM" src="https://user-images.githubusercontent.com/120754555/213306979-6ffc3760-a436-4fb9-9818-ab64111f78bd.png">
After fixes: 
![Screen Shot 2023-01-18 at 3 50 44 PM](https://user-images.githubusercontent.com/120754555/213307077-1177b14c-8e4e-44ac-95aa-7bc208cd2b4c.png)

2023-01-19 13:37 UTC, jrassa commented
> Looking for some help with fixing the fonts of "Firefox" and "Chrome" in the browser recommendation section under the help tab. I think the styling of the text was lost in the upgrade and am unfamiliar with css Pseudo-elements.

Looks like the fontawesome font was being applied to the text as well, which looked fine with previous version.

In `getting-started-help.component.html`, you just need to separate the text from the icon.

Before:
```
<pre><span class="fa fa-3x fa-firefox"> Firefox</span>    <span class="fa fa-3x fa-chrome"> Chrome</span></pre>
```

After:
```html
<pre>
	<span class="fa fa-3x fa-firefox"></span>
	<span class="ml-3" style="font-size: 3em">Firefox</span>
	<span class="fa fa-3x fa-chrome"></span>
	<span class="ml-3" style="font-size: 3em">Chrome</span>
</pre>
```

2023-01-19 13:40 UTC, jrassa commented
Since you will already be making changes there, can we also updated the firefox and chrome icons to use the FA5 styles.

Replace `fa fa-3x fa-firefox` with `fa-brands fa-3x fa-firefox`
Replace `fa fa-3x fa-chrome` with `fa-brands fa-3x fa-chrome`

2023-02-01 14:03 UTC, jrassa approved these changes

2023-02-01 14:04 UTC, merged