stylelint integration into the build
bluehalo/ngx-starter pull request #33
Opened 2018-11-25 16:44 UTC by reblace

Integrating style (scss) linting into the build.

- Using `stylelint` along with most default options for scss linting
- Made some minor changes to style files to fix some lint issues
- Disabled a couple of the lint rules to accommodate some harder to follow rules

2018-11-25 21:01 UTC, brianghig requested changes
README docs look like the only thing that's missing for this update. Thanks for incorporating another automated code analysis tool!

2018-11-25 21:01 UTC, brianghig commented on package.json
> +    "build": "npm run lint && ng build",
@reblace thanks for including these lint tasks with each build. Should we add these details to the top-level README under the NPM Scripts section? https://github.com/asymmetrik/ngx-starter#npm-scripts

2018-11-25 21:04 UTC, reblace commented on package.json
> +    "build": "npm run lint && ng build",
Yeah, do we want linting to happen with the build? Or, do we only want it as part of a ci build?

2018-11-25 21:47 UTC, reblace commented on package.json
> +    "build": "npm run lint && ng build",
I collapsed both linting operations into the single lint npm script. We'll leave running the lint as part of the build for now.

2018-11-27 02:06 UTC, brianghig approved these changes

2018-11-27 02:11 UTC, merged