BUG: set initial admin when creating team
bluehalo/ngx-starter pull request #75
Opened 2019-09-10 18:51 UTC by abemac

Currently, initial admin will be current user, regardless of who is specified.

2019-09-10 20:43 UTC, jrassa commented
Are you working on a corresponding PR for node-rest-starter?  As is an error is now thrown when trying to create a team.

2019-09-11 03:26 UTC, abemac commented
@jrassa yes, I am

2019-09-12 00:01 UTC, brianghig requested changes

2019-09-12 00:01 UTC, brianghig commented on src/app/core/teams/teams.service.ts
> +				firstAdmin: null === firstAdmin ? null : firstAdmin._id || firstAdmin
@abemac can we please get a test for this logic? Looking at it, I'm not sure whether the `||` applies to the full statement or just the last two parameters. Might be nice to type-check "firstAdmin" as a `string | User` too. Thanks for fixing this bug!

2019-09-12 12:53 UTC, jrassa commented on src/app/core/teams/teams.service.ts
> +				firstAdmin: null === firstAdmin ? null : firstAdmin._id || firstAdmin
Can we simplify things and just make "firstAdmin" a `string` and ensure that the id string is always passed in?

2019-09-12 15:42 UTC, brianghig commented on src/app/core/teams/teams.service.ts
> +				firstAdmin: null === firstAdmin ? null : firstAdmin._id || firstAdmin
@jrassa @abemac  That would certainly work. Does it make sense to link this by User ID or by Username? My concern with linking by User ID is that a user's profile can be destroyed and recreated (mostly in the PKI scenario), and all of their Team Admin Ownership would be lost.

2019-09-12 16:04 UTC, jrassa commented on src/app/core/teams/teams.service.ts
> +				firstAdmin: null === firstAdmin ? null : firstAdmin._id || firstAdmin
I'm not really sure what scenario would cause a user's profile to be destroyed.  When using PKI, if a user's PKI dn were to change a new profile would be created.  In that scenario, I would expect that the user would contact support and the accounts could be merged/reconciled.

2019-09-12 16:16 UTC, brianghig commented on src/app/core/teams/teams.service.ts
> +				firstAdmin: null === firstAdmin ? null : firstAdmin._id || firstAdmin
In my experience, we don't do a good job of managing new DNs with the same Usernames. It causes conflicts when we pull cache entries by DN, and try to sync that up with DB records by username.

In general, I'd rephrase this to a question of, "how should we uniquely identify users?" Username seems like a common platform between "local" and "pki" strategies, especially since it is how users and administrators search for User-based content.

2019-09-12 18:59 UTC, jrassa commented on src/app/core/teams/teams.service.ts
> +				firstAdmin: null === firstAdmin ? null : firstAdmin._id || firstAdmin
>In my experience, we don't do a good job of managing new DNs with the same Usernames. It causes conflicts when we pull cache entries by DN, and try to sync that up with DB records by username.

I believe that we have improved on this recently.  https://github.com/Asymmetrik/node-rest-starter/commit/d9091757b3106aa380ac938cc9f33660b5577e3d#diff-1687462e99fc8498e54065d21f1f5599L128

>In general, I'd rephrase this to a question of, "how should we uniquely identify users?" Username seems like a common platform between "local" and "pki" strategies, especially since it is how users and administrators search for User-based content.

That is a detail of the user management strategy that the rest of the application shouldn't need to be aware.  Using generated ids, as we are now, decouples the rest of the application from the details of user management.

2019-09-16 13:16 UTC, merged